services:
  - type: web
    name: listing-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: NODE_ENV
        value: production
